"""Film effect layer compositing."""

from .compositor import composite_layers
from .creative_diffusion import (
    CREATIVE_DIFFUSION_VERSION,
    CreativeDiffusionProfile,
    apply_creative_diffusion_linear,
    validate_creative_diffusion_profile,
)
from .effects import (
    density_halation_layer,
    dust_scratch_layer,
    grain_residual_layer,
    halation_layer,
    physical_halation_layer,
)
from .global_resample import (
    CHUNK_INVARIANT_GLOBAL_RESAMPLE_VERSION,
    GLOBAL_RESAMPLE_VERSION,
    ChunkInvariantRowStageMetadata,
    GlobalResampleExecutionMetadata,
    GlobalResamplePlan,
    GlobalRowReadRecord,
    StagedGlobalField,
    build_chunk_invariant_global_stage,
    build_chunk_invariant_global_stage_from_rows,
    build_shape_stable_global_stage,
    plan_chunk_invariant_global_resample,
    plan_shape_stable_global_resample,
    reconstruct_chunk_invariant_full,
    reconstruct_chunk_invariant_tiled,
    reconstruct_chunk_invariant_window,
    reconstruct_shape_stable_full,
    reconstruct_shape_stable_tiled,
    reconstruct_shape_stable_window,
)
from .gradient_window import (
    GRADIENT_WINDOW_VERSION,
    GradientWindowMetadata,
    array_scalar_window_reader,
    coordinate_gradient_window,
    coordinate_gradient_window_from_array,
)
from .halation_controls import (
    HALATION_PRESETS,
    HalationPreset,
    PhysicalHalationControls,
    build_physical_halation_layer,
    describe_physical_halation_controls,
    get_halation_preset,
    halation_gui_schema,
    list_halation_presets,
    resolve_physical_halation_controls,
    validate_physical_halation_controls,
)
from .halation_dag import (
    DENSITY_FAMILY,
    HALATION_DAG_VERSION,
    PHYSICAL_COLOUR_FAMILY,
    REQUIRED_INTEGRATION_CAPABILITIES,
    FieldLifetime,
    HalationCapabilityBinding,
    HalationFieldNode,
    HalationResourcePlan,
    available_halation_integration_capabilities,
    build_halation_resource_plan,
    resolve_halation_integration_capability_bindings,
    validate_halation_capability_bindings,
    validate_halation_nodes,
)
from .layers import FilmLayer, layer_metrics
from .staged_density import (
    STAGED_DENSITY_VERSION,
    DensityGlobalContextMetadata,
    StagedDensityExecutionMetadata,
    execute_staged_density_halation_default,
    materialized_density_halation_v2_reference,
)
from .staged_density_adapter import composite_staged_density_rows
from .streaming_percentile import (
    STREAMING_PERCENTILE_VERSION,
    StreamingPercentileResult,
    exact_streaming_percentiles,
)
from .tiled_effects import (
    DustScratchContext,
    DustScratchExecutionMetadata,
    build_dust_scratch_context,
    composite_dust_scratch_tiled,
    composite_simple_halation_tiled,
    dust_scratch_alpha_window,
    simple_halation_required_halo,
)
from .tiled_grain import (
    GRAIN_BLUR_HALO,
    StagedGrainMetadata,
    staged_grain_residual_layer,
)

__all__ = [
    "CHUNK_INVARIANT_GLOBAL_RESAMPLE_VERSION",
    "CREATIVE_DIFFUSION_VERSION",
    "DENSITY_FAMILY",
    "GLOBAL_RESAMPLE_VERSION",
    "GRADIENT_WINDOW_VERSION",
    "GRAIN_BLUR_HALO",
    "HALATION_DAG_VERSION",
    "HALATION_PRESETS",
    "PHYSICAL_COLOUR_FAMILY",
    "REQUIRED_INTEGRATION_CAPABILITIES",
    "STAGED_DENSITY_VERSION",
    "STREAMING_PERCENTILE_VERSION",
    "ChunkInvariantRowStageMetadata",
    "CreativeDiffusionProfile",
    "DensityGlobalContextMetadata",
    "DustScratchContext",
    "DustScratchExecutionMetadata",
    "FieldLifetime",
    "FilmLayer",
    "GlobalResampleExecutionMetadata",
    "GlobalResamplePlan",
    "GlobalRowReadRecord",
    "GradientWindowMetadata",
    "HalationCapabilityBinding",
    "HalationFieldNode",
    "HalationPreset",
    "HalationResourcePlan",
    "PhysicalHalationControls",
    "StagedDensityExecutionMetadata",
    "StagedGlobalField",
    "StagedGrainMetadata",
    "StreamingPercentileResult",
    "apply_creative_diffusion_linear",
    "array_scalar_window_reader",
    "available_halation_integration_capabilities",
    "build_chunk_invariant_global_stage",
    "build_chunk_invariant_global_stage_from_rows",
    "build_dust_scratch_context",
    "build_halation_resource_plan",
    "build_physical_halation_layer",
    "build_shape_stable_global_stage",
    "composite_dust_scratch_tiled",
    "composite_layers",
    "composite_simple_halation_tiled",
    "composite_staged_density_rows",
    "coordinate_gradient_window",
    "coordinate_gradient_window_from_array",
    "density_halation_layer",
    "describe_physical_halation_controls",
    "dust_scratch_alpha_window",
    "dust_scratch_layer",
    "exact_streaming_percentiles",
    "execute_staged_density_halation_default",
    "get_halation_preset",
    "grain_residual_layer",
    "halation_gui_schema",
    "halation_layer",
    "layer_metrics",
    "list_halation_presets",
    "materialized_density_halation_v2_reference",
    "physical_halation_layer",
    "plan_chunk_invariant_global_resample",
    "plan_shape_stable_global_resample",
    "reconstruct_chunk_invariant_full",
    "reconstruct_chunk_invariant_tiled",
    "reconstruct_chunk_invariant_window",
    "reconstruct_shape_stable_full",
    "reconstruct_shape_stable_tiled",
    "reconstruct_shape_stable_window",
    "resolve_halation_integration_capability_bindings",
    "resolve_physical_halation_controls",
    "simple_halation_required_halo",
    "staged_grain_residual_layer",
    "validate_creative_diffusion_profile",
    "validate_halation_capability_bindings",
    "validate_halation_nodes",
    "validate_physical_halation_controls",
]
