"""Film effect layer compositing."""

from .compositor import composite_layers
from .effects import density_halation_layer, dust_scratch_layer, grain_residual_layer, halation_layer, physical_halation_layer
from .halation_controls import (
    HALATION_PRESETS,
    HalationPreset,
    PhysicalHalationControls,
    build_physical_halation_layer,
    describe_physical_halation_controls,
    get_halation_preset,
    halation_gui_schema,
    list_halation_presets,
    resolve_physical_halation_controls,
    validate_physical_halation_controls,
)
from .halation_dag import (
    DENSITY_FAMILY,
    HALATION_DAG_VERSION,
    PHYSICAL_COLOUR_FAMILY,
    REQUIRED_INTEGRATION_CAPABILITIES,
    FieldLifetime,
    HalationFieldNode,
    HalationResourcePlan,
    build_halation_resource_plan,
    validate_halation_nodes,
)
from .global_resample import (
    GLOBAL_RESAMPLE_VERSION,
    GlobalResampleExecutionMetadata,
    GlobalResamplePlan,
    StagedGlobalField,
    build_shape_stable_global_stage,
    plan_shape_stable_global_resample,
    reconstruct_shape_stable_full,
    reconstruct_shape_stable_tiled,
    reconstruct_shape_stable_window,
)
from .layers import FilmLayer, layer_metrics
from .tiled_grain import (
    GRAIN_BLUR_HALO,
    StagedGrainMetadata,
    staged_grain_residual_layer,
)
from .streaming_percentile import (
    STREAMING_PERCENTILE_VERSION,
    StreamingPercentileResult,
    exact_streaming_percentiles,
)
from .tiled_effects import (
    DustScratchContext,
    DustScratchExecutionMetadata,
    build_dust_scratch_context,
    composite_dust_scratch_tiled,
    composite_simple_halation_tiled,
    dust_scratch_alpha_window,
    simple_halation_required_halo,
)

__all__ = [
    "FilmLayer",
    "FieldLifetime",
    "GLOBAL_RESAMPLE_VERSION",
    "GlobalResampleExecutionMetadata",
    "GlobalResamplePlan",
    "HALATION_DAG_VERSION",
    "HalationFieldNode",
    "HalationResourcePlan",
    "GRAIN_BLUR_HALO",
    "DustScratchContext",
    "DustScratchExecutionMetadata",
    "HALATION_PRESETS",
    "HalationPreset",
    "PhysicalHalationControls",
    "PHYSICAL_COLOUR_FAMILY",
    "DENSITY_FAMILY",
    "REQUIRED_INTEGRATION_CAPABILITIES",
    "StagedGrainMetadata",
    "StagedGlobalField",
    "STREAMING_PERCENTILE_VERSION",
    "StreamingPercentileResult",
    "build_physical_halation_layer",
    "build_halation_resource_plan",
    "build_shape_stable_global_stage",
    "build_dust_scratch_context",
    "composite_layers",
    "composite_dust_scratch_tiled",
    "composite_simple_halation_tiled",
    "density_halation_layer",
    "describe_physical_halation_controls",
    "dust_scratch_layer",
    "dust_scratch_alpha_window",
    "exact_streaming_percentiles",
    "grain_residual_layer",
    "halation_layer",
    "get_halation_preset",
    "halation_gui_schema",
    "list_halation_presets",
    "physical_halation_layer",
    "plan_shape_stable_global_resample",
    "reconstruct_shape_stable_full",
    "reconstruct_shape_stable_tiled",
    "reconstruct_shape_stable_window",
    "resolve_physical_halation_controls",
    "simple_halation_required_halo",
    "staged_grain_residual_layer",
    "validate_physical_halation_controls",
    "validate_halation_nodes",
    "layer_metrics",
]
