# @package model
mamba:
  variant: "tiny"
  depths: [2, 3, 8, 3]
  dim: 80
  in_dim: 32
  mlp_ratio: 4
  d_state: 8
  d_conv: 3
  expand: 1
  conv_stages: [0, 1]
  mamba_stages: [2, 3]
  attn_in_last_blocks: true
  window_size: [8, 8, 14, 7]
  drop_path_rate: 0.1
  scan_mode: "quad-directional"
