#!/usr/bin/env python3
"""Prepare and launch SDXL LoRA training with the official diffusers script.

This wrapper keeps local project policy in one place:

- use the checked manifest so rejected images stay out of training;
- write imagefolder-compatible metadata.jsonl for one film directory;
- pin the Hugging Face example script to diffusers v0.38.0, matching this repo.

Examples:
  python scripts/train_sdxl_lora.py --style portra_400 --dry-run
  python scripts/train_sdxl_lora.py --style portra_400 --steps 1 --output-dir outputs/smoke/portra_400
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MODEL = "stabilityai/stable-diffusion-xl-base-1.0"
DEFAULT_SCRIPT_URL = (
    "https://raw.githubusercontent.com/huggingface/diffusers/"
    "v0.38.0/examples/text_to_image/train_text_to_image_lora_sdxl.py"
)

FILM_CAPTIONS = {
    "ektar_100": "Kodak Ektar 100 film photograph, vivid saturated colors, ultra fine grain, analog photography",
    "hp5": "Ilford HP5 Plus 400 black and white film photograph, classic grain, rich tonality, analog photography",
    "portra_400": "Kodak Portra 400 film photograph, warm natural skin tones, fine grain, analog photography",
    "portra_800": "Kodak Portra 800 film photograph, warm natural colors, moderate grain, analog photography",
    "tri_x_400": "Kodak Tri-X 400 black and white film photograph, classic grain, high contrast, documentary photography",
    "velvia_50": "Fujifilm Velvia 50 slide film photograph, vivid saturated colors, deep shadows, fine grain",
    "vision3_250d": "Kodak Vision3 250D cinematic film photograph, daylight color, fine grain, analog cinematography",
    "vision3_500t": "Kodak Vision3 500T cinematic film photograph, tungsten color, film grain, analog cinematography",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Prepare metadata and launch SDXL LoRA training for one film stock."
    )
    parser.add_argument("--style", required=True, help="Film style name, e.g. portra_400")
    parser.add_argument(
        "--film-dir",
        type=Path,
        default=None,
        help="Image directory. Defaults to data/film_domain/<style>.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=ROOT / "data" / "processed" / "manifest.jsonl",
        help="Project manifest generated by scripts/build_data_manifest.py.",
    )
    parser.add_argument("--caption", default=None, help="Override training caption.")
    parser.add_argument("--include-val", action="store_true", help="Include manifest val split.")
    parser.add_argument(
        "--pretrained-model",
        default=DEFAULT_MODEL,
        help="Base SDXL model passed to the official script.",
    )
    parser.add_argument("--resolution", type=int, default=512)
    parser.add_argument("--rank", type=int, default=64)
    parser.add_argument("--steps", type=int, default=3000)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--gradient-accumulation-steps", type=int, default=1)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--lr-scheduler", default="constant")
    parser.add_argument("--lr-warmup-steps", type=int, default=0)
    parser.add_argument("--checkpointing-steps", type=int, default=500)
    parser.add_argument("--checkpoints-total-limit", type=int, default=3)
    parser.add_argument("--resume-from-checkpoint", default=None)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--mixed-precision", choices=["no", "fp16", "bf16"], default="fp16")
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output checkpoint directory. Defaults to outputs/sdxl_lora/<style>.",
    )
    parser.add_argument(
        "--official-script",
        type=Path,
        default=ROOT / ".cache" / "diffusers_examples" / "train_text_to_image_lora_sdxl.py",
        help="Cached official diffusers training script path.",
    )
    parser.add_argument("--official-script-url", default=DEFAULT_SCRIPT_URL)
    parser.add_argument("--refresh-official-script", action="store_true")
    parser.add_argument("--enable-xformers", action="store_true")
    parser.add_argument("--direct", action="store_true", help="Run script directly instead of accelerate launch.")
    parser.add_argument("--prepare-only", action="store_true", help="Only write metadata.jsonl.")
    parser.add_argument("--dry-run", action="store_true", help="Print command without starting training.")
    return parser.parse_args()


def to_abs(path: Path) -> Path:
    return path if path.is_absolute() else ROOT / path


def ensure_official_script(path: Path, url: str, refresh: bool) -> Path:
    path = to_abs(path)
    if path.exists() and not refresh:
        return path

    path.parent.mkdir(parents=True, exist_ok=True)
    print(f"Downloading official diffusers script: {url}")
    with urllib.request.urlopen(url, timeout=60) as response:
        content = response.read()
    path.write_bytes(content)
    return path


def load_manifest_records(manifest: Path, style: str, film_dir: Path, include_val: bool) -> list[dict]:
    manifest = to_abs(manifest)
    film_dir = to_abs(film_dir).resolve()
    if not manifest.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest}")

    records: list[dict] = []
    with manifest.open("r", encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            record = json.loads(line)
            if record.get("style") != style:
                continue
            if record.get("split") != "train" and not include_val:
                continue
            image_path = to_abs(Path(record["path"])).resolve()
            try:
                image_path.relative_to(film_dir)
            except ValueError:
                continue
            if image_path.exists():
                records.append({**record, "abs_path": image_path})

    if not records:
        raise RuntimeError(
            f"No usable manifest records found for style={style!r} in {film_dir}. "
            "Rebuild data/processed/manifest.jsonl first."
        )
    return records


def write_metadata(film_dir: Path, records: list[dict], caption: str) -> Path:
    film_dir = to_abs(film_dir).resolve()
    metadata_path = film_dir / "metadata.jsonl"
    with metadata_path.open("w", encoding="utf-8") as handle:
        for record in records:
            image_path = Path(record["abs_path"])
            rel_path = image_path.relative_to(film_dir).as_posix()
            text = caption or record.get("caption") or ""
            handle.write(json.dumps({"file_name": rel_path, "text": text}, ensure_ascii=True))
            handle.write("\n")
    return metadata_path


def build_command(args: argparse.Namespace, script_path: Path, film_dir: Path, output_dir: Path) -> list[str]:
    launcher = [sys.executable] if args.direct else [sys.executable, "-m", "accelerate.commands.launch"]
    command = launcher + [
        str(script_path),
        "--pretrained_model_name_or_path",
        args.pretrained_model,
        "--train_data_dir",
        str(film_dir),
        "--caption_column",
        "text",
        "--output_dir",
        str(output_dir),
        "--resolution",
        str(args.resolution),
        "--train_batch_size",
        str(args.batch_size),
        "--gradient_accumulation_steps",
        str(args.gradient_accumulation_steps),
        "--max_train_steps",
        str(args.steps),
        "--learning_rate",
        str(args.lr),
        "--lr_scheduler",
        args.lr_scheduler,
        "--lr_warmup_steps",
        str(args.lr_warmup_steps),
        "--checkpointing_steps",
        str(args.checkpointing_steps),
        "--checkpoints_total_limit",
        str(args.checkpoints_total_limit),
        "--rank",
        str(args.rank),
        "--mixed_precision",
        args.mixed_precision,
        "--seed",
        str(args.seed),
        "--dataloader_num_workers",
        str(args.num_workers),
        "--gradient_checkpointing",
    ]
    if args.caption:
        command += ["--validation_prompt", args.caption]
    if args.resume_from_checkpoint:
        command += ["--resume_from_checkpoint", args.resume_from_checkpoint]
    if args.enable_xformers:
        command.append("--enable_xformers_memory_efficient_attention")
    return command


def main() -> int:
    args = parse_args()
    film_dir = to_abs(args.film_dir or (ROOT / "data" / "film_domain" / args.style)).resolve()
    output_dir = to_abs(args.output_dir or (ROOT / "outputs" / "sdxl_lora" / args.style)).resolve()
    caption = args.caption or FILM_CAPTIONS.get(args.style, f"{args.style} film photograph, analog photography")

    records = load_manifest_records(args.manifest, args.style, film_dir, args.include_val)
    metadata_path = write_metadata(film_dir, records, caption)
    print(f"Prepared {len(records)} images for {args.style}")
    print(f"Metadata: {metadata_path}")
    print(f"Caption: {caption}")

    if args.prepare_only:
        return 0

    script_path = ensure_official_script(args.official_script, args.official_script_url, args.refresh_official_script)
    output_dir.mkdir(parents=True, exist_ok=True)
    command = build_command(args, script_path, film_dir, output_dir)

    print("Command:")
    print(subprocess.list2cmdline(command))
    if args.dry_run:
        return 0

    env = os.environ.copy()
    env.setdefault("PYTHONIOENCODING", "utf-8")
    env.setdefault("PYTHONUTF8", "1")
    return subprocess.run(command, cwd=ROOT, env=env, check=False).returncode


if __name__ == "__main__":
    raise SystemExit(main())
