"""Explicit physical-domain contracts and reference simulation primitives."""

from .contracts import (
    CANONICAL_DOMAIN_ORDER,
    DOMAIN_UNITS,
    PROFILE_BUNDLE_SCHEMA,
    QUALITY_TIERS,
    ComponentBinding,
    FilmProfileBundle,
    PhysicalDomain,
    PhysicalDomainArray,
    PhysicalScale,
    PhysicalUnit,
    QualityTier,
    QualityTierSpec,
    coordinate_counter_u64,
    density_to_transmittance,
    scene_exposure_from_working_image,
    transmittance_to_density,
)
from .reference_scatter import (
    REFERENCE_SCATTER_SCHEMA,
    ReferenceScatterProfile,
    ScatterComponent,
    apply_reference_scatter,
    gaussian_kernel_2d,
    gaussian_kernel_1d,
    profile_from_contract,
)
from .compiled_scatter import (
    CompiledScatterKernel,
    CompiledScatterProfile,
    apply_compiled_scatter,
    apply_compiled_scatter_row_tiled,
    compile_scatter_profile,
)
from .pyramid_scatter import (
    PyramidScatterComponent,
    PyramidScatterProfile,
    apply_pyramid_scatter,
    compile_pyramid_scatter_profile,
)
from .developed_structure import (
    DevelopedStructureContext,
    build_bw_silver_context,
    build_colour_dye_cloud_context,
    render_developed_structure,
    render_developed_structure_region,
)
from .structure_compiler import (
    MarginalProfile,
    correlated_normal_region,
    counter_normal_region,
    render_marginal,
    render_marginal_region,
)

__all__ = [
    "CANONICAL_DOMAIN_ORDER",
    "DOMAIN_UNITS",
    "PROFILE_BUNDLE_SCHEMA",
    "QUALITY_TIERS",
    "ComponentBinding",
    "CompiledScatterKernel",
    "CompiledScatterProfile",
    "FilmProfileBundle",
    "MarginalProfile",
    "DevelopedStructureContext",
    "PhysicalDomain",
    "PhysicalDomainArray",
    "PhysicalScale",
    "PhysicalUnit",
    "PyramidScatterComponent",
    "PyramidScatterProfile",
    "QualityTier",
    "QualityTierSpec",
    "REFERENCE_SCATTER_SCHEMA",
    "ReferenceScatterProfile",
    "ScatterComponent",
    "apply_compiled_scatter",
    "apply_compiled_scatter_row_tiled",
    "apply_pyramid_scatter",
    "build_bw_silver_context",
    "build_colour_dye_cloud_context",
    "apply_reference_scatter",
    "coordinate_counter_u64",
    "density_to_transmittance",
    "compile_scatter_profile",
    "compile_pyramid_scatter_profile",
    "correlated_normal_region",
    "counter_normal_region",
    "gaussian_kernel_1d",
    "gaussian_kernel_2d",
    "profile_from_contract",
    "render_developed_structure",
    "render_developed_structure_region",
    "render_marginal",
    "render_marginal_region",
    "scene_exposure_from_working_image",
    "transmittance_to_density",
]
